[package]
name = "m34wq_kvm_switch"
version = "0.0.2"
build = "build.rs"

[dependencies]
hidapi = "1.3.3"

[build-dependencies]
winres = "0.1"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = 'abort'